/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ru_nsu_sberlab_gameintegration_tasks_BlockchainDataRequestTask */

#ifndef _Included_ru_nsu_sberlab_gameintegration_tasks_BlockchainDataRequestTask
#define _Included_ru_nsu_sberlab_gameintegration_tasks_BlockchainDataRequestTask
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ru_nsu_sberlab_gameintegration_tasks_BlockchainDataRequestTask
 * Method:    sendBlockChangeC
 * Signature: (Lru/nsu/sberlab/gameintegration/data/Block;)V
 */
JNIEXPORT void JNICALL Java_ru_nsu_sberlab_gameintegration_tasks_BlockchainDataRequestTask_sendBlockChangeC
  (JNIEnv *, jclass, jobject);

#ifdef __cplusplus
}
#endif
#endif
