/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ru_nsu_sberlab_gameintegration_tasks_CDataRequestTask */

#ifndef _Included_ru_nsu_sberlab_gameintegration_tasks_CDataRequestTask
#define _Included_ru_nsu_sberlab_gameintegration_tasks_CDataRequestTask
#ifdef __cplusplus
extern "C" {
#endif
#undef ru_nsu_sberlab_gameintegration_tasks_CDataRequestTask_TIME_REQUEST
#define ru_nsu_sberlab_gameintegration_tasks_CDataRequestTask_TIME_REQUEST 1500L
/*
 * Class:     ru_nsu_sberlab_gameintegration_tasks_CDataRequestTask
 * Method:    getBlockChangeC
 * Signature: ()Lru/nsu/sberlab/gameintegration/data/Block;
 */
JNIEXPORT jobject JNICALL Java_ru_nsu_sberlab_gameintegration_tasks_CDataRequestTask_getBlockChangeC
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
