/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ru_nsu_sberlab_cprogramintegration_BlockchainHandler */

#ifndef _Included_ru_nsu_sberlab_cprogramintegration_BlockchainHandler
#define _Included_ru_nsu_sberlab_cprogramintegration_BlockchainHandler
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ru_nsu_sberlab_cprogramintegration_BlockchainHandler
 * Method:    sendBlockChangeC
 * Signature: (IIIIII)V
 */
JNIEXPORT void JNICALL Java_ru_nsu_sberlab_cprogramintegration_BlockchainHandler_sendBlockChangeC
  (JNIEnv *, jclass, jint, jint, jint, jint, jint, jint);

/*
 * Class:     ru_nsu_sberlab_cprogramintegration_BlockchainHandler
 * Method:    sendStateChangeC
 * Signature: (IIIII)V
 */
JNIEXPORT void JNICALL Java_ru_nsu_sberlab_cprogramintegration_BlockchainHandler_sendStateChangeC
  (JNIEnv *, jclass, jint, jint, jint, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
