/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ru_nsu_sberlab_cprogramintegration_CDataExtractor */

#ifndef _Included_ru_nsu_sberlab_cprogramintegration_CDataExtractor
#define _Included_ru_nsu_sberlab_cprogramintegration_CDataExtractor
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ru_nsu_sberlab_cprogramintegration_CDataExtractor
 * Method:    getBlockChangeC
 * Signature: ()Lru/nsu/sberlab/cprogramintegration/Block;
 */
JNIEXPORT jobject JNICALL Java_ru_nsu_sberlab_cprogramintegration_CDataExtractor_getBlockChangeC
  (JNIEnv *, jclass);

/*
 * Class:     ru_nsu_sberlab_cprogramintegration_CDataExtractor
 * Method:    getStateChangeC
 * Signature: ()Lru/nsu/sberlab/cprogramintegration/State;
 */
JNIEXPORT jobject JNICALL Java_ru_nsu_sberlab_cprogramintegration_CDataExtractor_getStateChangeC
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
