/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ru_nsu_sberlab_launcher_Launcher */

#ifndef _Included_ru_nsu_sberlab_launcher_Launcher
#define _Included_ru_nsu_sberlab_launcher_Launcher
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ru_nsu_sberlab_launcher_Launcher
 * Method:    start
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_ru_nsu_sberlab_launcher_Launcher_start
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
