/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ru_nsu_sberlab_gameintegration_PlayerPositionHandler */

#ifndef _Included_ru_nsu_sberlab_gameintegration_PlayerPositionHandler
#define _Included_ru_nsu_sberlab_gameintegration_PlayerPositionHandler
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ru_nsu_sberlab_gameintegration_PlayerPositionHandler
 * Method:    getPlayerPositionC
 * Signature: ()Lru/nsu/sberlab/gameintegration/data/PlayerPosition;
 */
JNIEXPORT jobject JNICALL Java_ru_nsu_sberlab_gameintegration_PlayerPositionHandler_getPlayerPositionC
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
