/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ru_nsu_sberlab_gameintegration_tasks_StartTask */

#ifndef _Included_ru_nsu_sberlab_gameintegration_tasks_StartTask
#define _Included_ru_nsu_sberlab_gameintegration_tasks_StartTask
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ru_nsu_sberlab_gameintegration_tasks_StartTask
 * Method:    start
 * Signature: (Lru/nsu/sberlab/gameintegration/data/PlayerPosition;)V
 */
JNIEXPORT void JNICALL Java_ru_nsu_sberlab_gameintegration_tasks_StartTask_start
  (JNIEnv *, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
