/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ru_nsu_sberlab_gameintegration_StaticQueuesWrapper */

#ifndef _Included_ru_nsu_sberlab_gameintegration_StaticQueuesWrapper
#define _Included_ru_nsu_sberlab_gameintegration_StaticQueuesWrapper
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ru_nsu_sberlab_gameintegration_StaticQueuesWrapper
 * Method:    sendBlockChangeC
 * Signature: (Lru/nsu/sberlab/gameintegration/data/Block;)V
 */
JNIEXPORT void JNICALL Java_ru_nsu_sberlab_gameintegration_StaticQueuesWrapper_sendBlockChangeC
  (JNIEnv *, jclass, jobject);

/*
 * Class:     ru_nsu_sberlab_gameintegration_StaticQueuesWrapper
 * Method:    getBlockChangeC
 * Signature: ()Lru/nsu/sberlab/gameintegration/data/Block;
 */
JNIEXPORT jobject JNICALL Java_ru_nsu_sberlab_gameintegration_StaticQueuesWrapper_getBlockChangeC
  (JNIEnv *, jclass);

/*
 * Class:     ru_nsu_sberlab_gameintegration_StaticQueuesWrapper
 * Method:    init
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_ru_nsu_sberlab_gameintegration_StaticQueuesWrapper_init
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
